# Generated by Django 5.1.7 on 2026-03-27 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_order_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
