# Generated by Django 5.1.7 on 2026-07-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Stripe", "Stripe"), ("COD", "Cash on Delivery")],
                default="Stripe",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
